from dataclasses import dataclass, field


@dataclass
class SyncJob:
    """
    Represents a single sync operation:
    copy folders from one source repo into one target repo.
    """

    # Source
    source_repo: str
    source_branch: str = "main"

    # Folders to copy
    folders: dict = field(default_factory=dict)

    # If True, all files land flat in target_folder (no subfolders recreated)
    flatten: bool = False

    # Target
    target_repo: str = "kolioaris/kolioaris.xyz"
    target_base_branch: str = "master"
    new_branch_name: str = "kolioaris-bot/sync"

    # --- Pull request ---
    pr_title: str = "[Bot] Sync folders"
    pr_body: str = "Automated folder sync via bot."

SYNC_JOBS = [

    SyncJob(
        source_repo="kolioaris/sh-conv",
        source_branch="main",
        folders={
            "docs":   "docs/sh-conv",       # copy src/utils → lib/utils
        },
        flatten=False,
        target_repo="kolioaris/kolioaris.xyz",
        target_base_branch="master",
        new_branch_name="kolioaris-bot/sync",
        pr_title="[Bot] Sync documentation from sh-conv",
        pr_body="""
This PR was automatically generated by the bot to sync the documentation from `kolioaris/sh-conv` to `kolioaris/kolioaris.xyz`. It includes the latest updates to the documentation folder, making sure kolioaris.xyz has the most up-to-date information from the backend project.

Folders synced:
- `docs/` from `kolioaris/sh-conv` → `docs/sh-conv` in `kolioaris/kolioaris.xyz`
""",
    ),
]